// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  SIGNUP_RATELIMIT: RateLimit;
  SUBSCRIBERS: D1Database;
  STATUS: KVNamespace;
}
